//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResultProvider.OpenLigaDb.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResultProvider.OpenLigaDb.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;MatchID&quot;: 37181,
        ///    &quot;MatchDateTime&quot;: &quot;2016-06-10T21:00:00&quot;,
        ///    &quot;TimeZoneID&quot;: &quot;W. Europe Standard Time&quot;,
        ///    &quot;MatchDateTimeUTC&quot;: &quot;2016-06-10T19:00:00Z&quot;,
        ///    &quot;Team1&quot;: {
        ///      &quot;TeamId&quot;: 144,
        ///      &quot;TeamName&quot;: &quot;Frankreich&quot;,
        ///      &quot;TeamIconUrl&quot;: &quot;http://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/20px-Flag_of_France.svg.png&quot;
        ///    },
        ///    &quot;Team2&quot;: {
        ///      &quot;TeamId&quot;: 143,
        ///      &quot;TeamName&quot;: &quot;Rumänien&quot;,
        ///      &quot;TeamIconUrl&quot;: &quot;http://upload.wikimedia.org/wikipedia/commons/thumb/7/73/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string em2016 {
            get {
                return ResourceManager.GetString("em2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///	&quot;MatchID&quot;: 39002,
        ///	&quot;MatchDateTime&quot;: &quot;2016-06-10T21:00:00&quot;,
        ///	&quot;TimeZoneID&quot;: &quot;W. Europe Standard Time&quot;,
        ///	&quot;MatchDateTimeUTC&quot;: &quot;2016-06-10T19:00:00Z&quot;,
        ///	&quot;Team1&quot;: {
        ///		&quot;TeamId&quot;: 144,
        ///		&quot;TeamName&quot;: &quot;Frankreich&quot;,
        ///		&quot;TeamIconUrl&quot;: &quot;http://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/20px-Flag_of_France.svg.png&quot;
        ///	},
        ///	&quot;Team2&quot;: {
        ///		&quot;TeamId&quot;: 143,
        ///		&quot;TeamName&quot;: &quot;Rumänien&quot;,
        ///		&quot;TeamIconUrl&quot;: &quot;http://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/200px-Flag_of_R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string realem2016 {
            get {
                return ResourceManager.GetString("realem2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///	&quot;MatchID&quot;: 39002,
        ///	&quot;MatchDateTime&quot;: &quot;2016-06-10T21:00:00&quot;,
        ///	&quot;TimeZoneID&quot;: &quot;W. Europe Standard Time&quot;,
        ///	&quot;MatchDateTimeUTC&quot;: &quot;2016-06-10T19:00:00Z&quot;,
        ///	&quot;Team1&quot;: {
        ///		&quot;TeamId&quot;: 144,
        ///		&quot;TeamName&quot;: &quot;Frankreich&quot;,
        ///		&quot;TeamIconUrl&quot;: &quot;http://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/20px-Flag_of_France.svg.png&quot;
        ///	},
        ///	&quot;Team2&quot;: {
        ///		&quot;TeamId&quot;: 143,
        ///		&quot;TeamName&quot;: &quot;Rumänien&quot;,
        ///		&quot;TeamIconUrl&quot;: &quot;http://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/200px-Flag_of_R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
    }
}
